### ISSUE TITLE
Translation Reflection Timing

### ISSUE THREAD

**Issue by Pawllo2** [django/django-docs-translations#10]
Hi team,

I started translating Django documentation into Japanese last year. It was reflected to the actual documentation in January (so amazing!) but I added some translation from that point.
I'd like to know how often it will be reflected. Or should I do something for this?

I'm still struggling to understand Github and Transifex so I'm sorry if this question doesn't make sense.

Thanks!

**Comment by claudep** [comment]
Updates happen from time to time, with no fixed schedule. There will be an update before 1.11 final.
I'd suggest asking/discussing this on the django-i18n mailing list (I've just asked to add this to the repo description).
https://groups.google.com/forum/#!forum/django-i18n

**Comment by Pawllo2** [comment]
Thank you for that quick reply. I will look at the group.
