### ISSUE TITLE
Typo in french translation

### ISSUE THREAD

**Issue by LLyaudet** [django/django-docs-translations#26]
Hello,

I found the following typo :
BACKEND est un chemin Python pointé vers **ue** classe de moteur de gabarit 
'ue' should be 'une'
here :
https://docs.djangoproject.com/fr/3.1/topics/templates/
Le langage de gabarit de Django

Sorry for not submitting a PR but my search on Github with "gabarit" in django org yield no corresponding match.

Best regards,
     Laurent Lyaudet

**Comment by claudep** [comment]
Merci beaucoup pour le signalement, la correction se fait directement dans Transifex (https://www.transifex.com/django/django-docs/) et pas par Pull request. J'ai fait la correction, elle devrait être en ligne dans les prochaines semaines.
