### ISSUE TITLE
Add Italian translation

### ISSUE THREAD

**Issue by pauloxnet** [django/django-docs-translations#28]
Italian translations of required resources 'index', 'intro' and 'website-strings' are completed.

Other resources 'contents', 'faq', 'glossary', 'misc' are also fully translated.

I've just opened the PR #29 with the new Italian translations.

**Comment by giulianomandotti** [comment]
hi, i am quite new to django, but with passion to documentation. i discovered this group via the djangonews. i will be pleased to give my contribute.

**Comment by pauloxnet** [comment]
Hi @giulianomandotti I'm happy to read your message.
Please join the Django docs team on transifex to help us translating Django and its documentation in Italian:
https://www.transifex.com/signup/?join_project=django-docs
