### ISSUE TITLE
Migration to new Transifex CLI

### ISSUE THREAD

**Issue by m-aciek** [django/django-docs-translations#35]
Current Transifex CLI, used in this project, is deprecated and will sunset (whatever it means?) on Nov 30, 2022. [1]

We should probably migrate to the new CLI. I started to work on a very similar migration for a script based on this repository's script: https://github.com/python/python-docs-pl/pull/23.

[1] https://docs.transifex.com/client/introduction

**Comment by claudep** [comment]
Personally I'm burned out by Transifex and its (catastrophic) changes. Feel free to work on this.

**Comment by comradekingu** [comment]
Weblate manages its docs on Weblate, and uses Django :)

**Comment by claudep** [comment]
I dream of a Django-dedicated Weblate instance. We just need someone to pay/maintain it.

**Comment by comradekingu** [comment]
@claudep Or use https://hosted.weblate.org/hosting/ ?

**Comment by claudep** [comment]
I think the ability to manage our own teams is important.

**Comment by comradekingu** [comment]
I tend to disagree, but it is possible to add the reviewers you want on Hosted.

**Comment by m-aciek** [comment]
Old thread, but: Weblate 4.15 added [team management](https://docs.weblate.org/en/latest/admin/access.html#team-administrators) on shared instances.
