### ISSUE TITLE
Update About

### ISSUE THREAD

**Issue by alond-ra** [django/django-docs-translations#37]
Hello!
I noticed that the "About" in this repo contains a link to a google group for related discussions. However, the last topic in that group indicates that there is a new forum for it since 2021; May I change it?

I suggest this:
"Translations of the Django documentation. Questions and discussions happen on https://forum.djangoproject.com/c/internals/i18n/14 . The previously used group on Google Groups is no longer being used. If you are looking for old topics, you may be able to find them at https://groups.google.com/forum/#!forum/django-i18n ."

**Comment by claudep** [comment]
Thanks, that's a good suggestion! I'm not authorized to do such a change. @felixxm, maybe?

**Comment by felixxm** [comment]
@alond-ra Thanks :+1: Updated.
