### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by m-aciek** [django/django-docs-translations#8]
Polish translation of docs' intro is already complete. Is it possible to make it online along with Django 1.10.3? Would my pull request be merged?

**Comment by claudep** [comment]
Great, I'll add it as soon as the robots.txt issue for translated docs is sorted out.

**Comment by m-aciek** [comment]
Currently there is Polish on the list of languages in the bottom right corner, but it leads to HTTP 404 page on https://docs.djangoproject.com/pl/1.10/ .

**Comment by claudep** [comment]
Yes, it always takes a bit of time before translated docs are produced. @timgraham can you check in the next hours?

**Comment by m-aciek** [comment]
Works like a charm :D! https://docs.djangoproject.com/pl/1.10/
Thanks, @claudep , @tkajtoch !
